### ISSUE TITLE
RuntimeError: Input type (torch.cuda.ByteTensor) and weight type (torch.cuda.HalfTensor) should be the same

### ISSUE THREAD

**Issue by mitra137400** [naseemap47/YOLO-NAS#22]
HI
I did the training with yolo_nas_l model on my custom dataset with one class and the training is over
I get the following error when I try to run the inference.py
How can I fix this error?
i did this 
python inference.py --data ./data.yaml --model yolo_nas_l --weight ./runs/train0/ckpt_best.pth --source ./3_F.jpg --conf 0.45

The console stream is logged into /home/kripl/sg_logs/console.log
[2023-07-04 12:24:54] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-07-04 12:24:55] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-07-04 12:24:55] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-07-04 12:24:55] WARNING - export.py - Failed to import pytorch_quantization
[2023-07-04 12:24:55] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
[2023-07-04 12:24:57] INFO - checkpoint_utils.py - Successfully loaded model weights from ./runs/train0/ckpt_best.pth EMA checkpoint.
Class Names:  ['sholi']
[2023-07-04 12:24:58] INFO - pipelines.py - Fusing some of the model's layers. If this takes too much memory, you can deactivate it by setting `fuse_model=False`
Traceback (most recent call last):
  File "/home/kripl/mitra/YOLO-NAS-master/inference.py", line 69, in <module>
    labels, class_names = get_bbox(img)
  File "/home/kripl/mitra/YOLO-NAS-master/inference.py", line 47, in get_bbox
    preds = next(model.predict(img_rgb, conf=args['conf'])._images_prediction_lst)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/super_gradients/training/models/detection_models/customizable_detector.py", line 177, in predict
    return pipeline(images)  # type: ignore
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 96, in __call__
    return self.predict_images(inputs, batch_size)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 111, in predict_images
    return self._combine_image_prediction_to_images(result_generator, n_images=len(images))
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 290, in _combine_image_prediction_to_images
    images_predictions = [next(iter(images_predictions))]
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 149, in _generate_prediction_result
    yield from self._generate_prediction_result_single_batch(batch_images)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 176, in _generate_prediction_result_single_batch
    model_output = self.model(torch_inputs)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/super_gradients/training/models/detection_models/customizable_detector.py", line 87, in forward
    x = self.backbone(x)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/super_gradients/modules/detection_modules.py", line 80, in forward
    x = getattr(self, layer)(x)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/super_gradients/training/models/detection_models/yolo_nas/yolo_stages.py", line 138, in forward
    return self.conv(x)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/super_gradients/modules/qarepvgg_block.py", line 179, in forward
    return self.se(self.nonlinearity(self.rbr_reparam(inputs)))
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.ByteTensor) and weight type (torch.cuda.HalfTensor) should be the same

**Comment by Tomosawa** [comment]
I also encountered this problem, slightly different, but almost the same problem, I hope there is a solution. The specific error information is as follows:

conv.py", line 459, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (unsigned char) and bias type (struct c10::Half) should be the same

**Comment by mitra137400** [comment]
Hi Tomosawa
i think this error is for super-gradients version
i did pip install super-gradients==3.1.1 and my error changed to 
The console stream is logged into /home/kripl/sg_logs/console.log
[2023-07-05 12:24:32] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-07-05 12:24:34] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-07-05 12:24:34] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-07-05 12:24:34] WARNING - export.py - Failed to import pytorch_quantization
[2023-07-05 12:24:34] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
[2023-07-05 12:24:36] INFO - checkpoint_utils.py - Successfully loaded model weights from ./runs/train0/ckpt_best.pth EMA checkpoint.
Class Names:  ['sholi']
Traceback (most recent call last):
  File "/home/kripl/mitra/YOLO-NAS-master/inference.py", line 69, in <module>
    labels, class_names = get_bbox(img)
  File "/home/kripl/mitra/YOLO-NAS-master/inference.py", line 52, in get_bbox
    plot_one_box(box[:4], img, label=f'{class_names[cs]} {cnf:.3}', color=colors[cs])
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/omegaconf/listconfig.py", line 218, in __getitem__
    self._format_and_raise(key=index, value=None, cause=e)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/omegaconf/listconfig.py", line 193, in __getitem__
    self._validate_get(index, None)
  File "/home/kripl/anaconda3/envs/yolo-nas10/lib/python3.9/site-packages/omegaconf/listconfig.py", line 86, in _validate_get
    raise KeyValidationError(
omegaconf.errors.KeyValidationError: ListConfig indices must be integers or slices, not int64
    full_key: 
    object_type=list
You try this command, maybe it will work for you

**Comment by naseemap47** [comment]
Hi @mitra137400 @Tomosawa ,
I think this issue came due to library versions
Try with new conda environment.
```
conda create -n yolo-nas python=3.9 -y
conda activate yolo-nas
conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch -y
pip install triton==2.0.0
pip install super-gradients
```
I think this will solve your issue
Let me know, this is working for you or NOT.
Thank you.

**Comment by musafzenbilci** [comment]
> Hi @mitra137400 @Tomosawa , I think this issue came due to library versions Try with new conda environment.
> 
> ```
> conda create -n yolo-nas python=3.9 -y
> conda activate yolo-nas
> conda install pytorch==1.12.1 torchvision==0.13.1 torchaudio==0.12.1 cudatoolkit=11.3 -c pytorch -y
> pip install triton==2.0.0
> pip install super-gradients
> ```
> 
> I think this will solve your issue Let me know, this is working for you or NOT. Thank you.

I have the exact same problem and this solution did not work.
Here is the output:
```The console stream is logged into /home/ubuntu/sg_logs/console.log
[2023-07-17 11:18:09] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-07-17 11:18:11] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-07-17 11:18:11] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-07-17 11:18:11] WARNING - export.py - Failed to import pytorch_quantization
[2023-07-17 11:18:11] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
[2023-07-17 11:18:13] INFO - checkpoint_utils.py - Successfully loaded model weights from checkpoints/YOLONASEXP/ckpt_best.pth EMA checkpoint.
Class Names:  {0: 'sedan', 1: 'minibus', 2: 'truck', 3: 'pickup', 4: 'bus', 5: 'cement truck', 6: 'trailer'}
[2023-07-17 11:18:14] INFO - pipelines.py - Fusing some of the model's layers. If this takes too much memory, you can deactivate it by setting `fuse_model=False`
Traceback (most recent call last):
  File "/home/ubuntu/yolo-trainer/yolov5/nasyolo/inference.py", line 69, in <module>
    labels, class_names = get_bbox(img)
  File "/home/ubuntu/yolo-trainer/yolov5/nasyolo/inference.py", line 47, in get_bbox
    preds = next(model.predict(img_rgb, conf=args['conf'])._images_prediction_lst)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/super_gradients/training/models/detection_models/customizable_detector.py", line 177, in predict
    return pipeline(images)  # type: ignore
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 96, in __call__
    return self.predict_images(inputs, batch_size)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 111, in predict_images
    return self._combine_image_prediction_to_images(result_generator, n_images=len(images))
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 290, in _combine_image_prediction_to_images
    images_predictions = [next(iter(images_predictions))]
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 149, in _generate_prediction_result
    yield from self._generate_prediction_result_single_batch(batch_images)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/super_gradients/training/pipelines/pipelines.py", line 176, in _generate_prediction_result_single_batch
    model_output = self.model(torch_inputs)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/super_gradients/training/models/detection_models/customizable_detector.py", line 87, in forward
    x = self.backbone(x)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/super_gradients/modules/detection_modules.py", line 80, in forward
    x = getattr(self, layer)(x)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/super_gradients/training/models/detection_models/yolo_nas/yolo_stages.py", line 138, in forward
    return self.conv(x)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/super_gradients/modules/qarepvgg_block.py", line 179, in forward
    return self.se(self.nonlinearity(self.rbr_reparam(inputs)))
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/torch/nn/modules/module.py", line 1130, in _call_impl
    return forward_call(*input, **kwargs)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 457, in forward
    return self._conv_forward(input, self.weight, self.bias)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/torch/nn/modules/conv.py", line 453, in _conv_forward
    return F.conv2d(input, weight, bias, self.stride,
RuntimeError: Input type (torch.cuda.ByteTensor) and weight type (torch.cuda.HalfTensor) should be the same ```

After running pip3 install super-gradients==3.1.1, error turns to 



The console stream is logged into /home/ubuntu/sg_logs/console.log
[2023-07-17 11:19:14] INFO - crash_tips_setup.py - Crash tips is enabled. You can set your environment variable to CRASH_HANDLER=FALSE to disable it
[2023-07-17 11:19:16] WARNING - __init__.py - Failed to import pytorch_quantization
[2023-07-17 11:19:16] WARNING - calibrator.py - Failed to import pytorch_quantization
[2023-07-17 11:19:16] WARNING - export.py - Failed to import pytorch_quantization
[2023-07-17 11:19:16] WARNING - selective_quantization_utils.py - Failed to import pytorch_quantization
[2023-07-17 11:19:21] INFO - checkpoint_utils.py - Successfully loaded model weights from checkpoints/YOLONASEXP/ckpt_best.pth EMA checkpoint.
Class Names:  {0: 'sedan', 1: 'minibus', 2: 'truck', 3: 'pickup', 4: 'bus', 5: 'cement truck', 6: 'trailer'}
Traceback (most recent call last):
  File "/home/ubuntu/yolo-trainer/yolov5/nasyolo/inference.py", line 69, in <module>
    labels, class_names = get_bbox(img)
  File "/home/ubuntu/yolo-trainer/yolov5/nasyolo/inference.py", line 52, in get_bbox
    plot_one_box(box[:4], img, label=f'{class_names[cs]} {cnf:.3}', color=colors[cs])
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/omegaconf/listconfig.py", line 218, in __getitem__
    self._format_and_raise(key=index, value=None, cause=e)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/omegaconf/listconfig.py", line 193, in __getitem__
    self._validate_get(index, None)
  File "/opt/conda/envs/yolo-nas/lib/python3.9/site-packages/omegaconf/listconfig.py", line 86, in _validate_get
    raise KeyValidationError(
omegaconf.errors.KeyValidationError: ListConfig indices must be integers or slices, not int64
    full_key: 
    object_type=list

**Comment by musafzenbilci** [comment]
SOLVED
in get_bbox function casting cs variable to int directly worked

```
def get_bbox(img):
    img_rgb = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)
    preds = next(model.predict(img_rgb, conf=args['conf'])._images_prediction_lst)
    class_names = preds.class_names
    dp = preds.prediction
    bboxes, confs, labels = np.array(dp.bboxes_xyxy), dp.confidence, dp.labels.astype(int)
    for box, cnf, cs in zip(bboxes, confs, labels):
        plot_one_box(box[:4], img, label=f'{class_names[int(cs)]} {cnf:.3}', color=colors[int(cs)])
    return labels, class_names
```

**Comment by naseemap47** [comment]
Hi @musafzenbilci 
Thank you for find solution for this issue.
I am updating this changed into code.
